@echo off
setlocal EnableDelayedExpansion

rem ============================================================================
rem  Sentinel Installer for Windows
rem  Run this once from the project directory to:
rem    1. Add the project directory to your user PATH (sentinel accessible everywhere)
rem    2. Set up a daily Windows Task Scheduler job for cloud model discovery
rem    3. Generate uninstall.bat for clean removal
rem    4. Self-delete after successful installation
rem ============================================================================

set "PROJECT_DIR=%~dp0"
if "%PROJECT_DIR:~-1%"=="\" set "PROJECT_DIR=%PROJECT_DIR:~0,-1%"

set "SENTINEL_HOME=%USERPROFILE%\.sentinel"
set "TASK_NAME=SentinelCloudModelProbe"
set "PROBE_SCRIPT=%PROJECT_DIR%\scripts\cloud_model_probe.py"
set "PROBE_WRAPPER=%PROJECT_DIR%\scripts\probe_runner.bat"

cls
echo.
echo  ===================================================================
echo   SENTINEL INSTALLER  ^|  Windows
echo  ===================================================================
echo.
echo   Project directory : %PROJECT_DIR%
echo   Sentinel home     : %SENTINEL_HOME%
echo   Task name         : %TASK_NAME%
echo.
echo   This installer will:
echo     [1] Check Python is installed
echo     [2] Install Python requirements  (requirements.txt)
echo     [3] Add project directory to your user PATH
echo     [4] Set up a daily Task Scheduler job for cloud model discovery
echo     [5] Generate uninstall.bat
echo     [6] Delete this install.bat
echo.
echo  -------------------------------------------------------------------

:confirm
set /p "CONFIRM=  Continue? [Y/n] "
if /i "%CONFIRM%"=="" goto :do_install
if /i "%CONFIRM%"=="y" goto :do_install
if /i "%CONFIRM%"=="yes" goto :do_install
if /i "%CONFIRM%"=="n" (
    echo.
    echo   Installation cancelled.
    exit /b 0
)
goto :confirm

:do_install

rem ── Step 1: Locate Python ────────────────────────────────────────────────────
echo.
echo   [1/6] Checking Python...
set "PYTHON_EXE="
where python >nul 2>nul && set "PYTHON_EXE=python"
if not defined PYTHON_EXE (
    where py >nul 2>nul && set "PYTHON_EXE=py"
)
if not defined PYTHON_EXE (
    for %%P in (
        "%LocalAppData%\Programs\Python\Python313\python.exe"
        "%LocalAppData%\Programs\Python\Python312\python.exe"
        "%LocalAppData%\Programs\Python\Python311\python.exe"
        "%LocalAppData%\Programs\Python\Python310\python.exe"
        "%ProgramFiles%\Python313\python.exe"
        "%ProgramFiles%\Python312\python.exe"
        "%ProgramFiles%\Python311\python.exe"
    ) do (
        if exist %%~P (
            set "PYTHON_EXE=%%~P"
            goto :python_found
        )
    )
)
:python_found
if not defined PYTHON_EXE (
    echo.
    echo   ERROR: Python was not found on this system.
    echo   Please install Python 3.10+ from https://python.org/downloads
    echo   then re-run install.bat.
    pause
    exit /b 1
)

for /f "tokens=*" %%V in ('"%PYTHON_EXE%" --version 2^>^&1') do set "PY_VER=%%V"
echo         Found: %PY_VER%  (%PYTHON_EXE%)

rem ── Step 2: Create venv + install requirements ───────────────────────────────
echo.
echo   [2/6] Installing Python requirements...
set "VENV_DIR=%PROJECT_DIR%\.venv"
if not exist "%VENV_DIR%\Scripts\python.exe" (
    echo         Creating virtual environment...
    "%PYTHON_EXE%" -m venv "%VENV_DIR%"
    if errorlevel 1 (
        echo   ERROR: Could not create virtual environment.
        pause
        exit /b 1
    )
)
set "VENV_PY=%VENV_DIR%\Scripts\python.exe"
"%VENV_PY%" -m pip install --upgrade pip --quiet
"%VENV_PY%" -m pip install -r "%PROJECT_DIR%\requirements.txt" --quiet
if errorlevel 1 (
    echo   ERROR: pip install failed. Check requirements.txt and your network connection.
    pause
    exit /b 1
)
echo         Done.

rem ── Step 3: Add project directory to user PATH ───────────────────────────────
echo.
echo   [3/6] Adding Sentinel to user PATH...

rem Use PowerShell to avoid setx's 1024-character PATH truncation bug.
powershell -NoProfile -Command "$cur = [System.Environment]::GetEnvironmentVariable('PATH','User'); if (($cur -split ';') -notcontains '%PROJECT_DIR%') { [System.Environment]::SetEnvironmentVariable('PATH', $cur + ';%PROJECT_DIR%', 'User'); Write-Host '        Added: %PROJECT_DIR%'; } else { Write-Host '        Already in PATH - skipped.'; }"

rem ── Step 4: Create Sentinel home directory ───────────────────────────────────
if not exist "%SENTINEL_HOME%" mkdir "%SENTINEL_HOME%"
if not exist "%SENTINEL_HOME%\logs" mkdir "%SENTINEL_HOME%\logs"

rem ── Step 5: Write probe_runner.bat (absolute paths — used by task scheduler) ─
echo.
echo   [4/6] Setting up daily cloud model discovery task...

(
    echo @echo off
    echo rem probe_runner.bat — generated by install.bat
    echo rem Runs the Ollama Cloud model probe using the project venv.
    echo rem Called by Windows Task Scheduler daily at 06:00.
    echo set "VENV_PY=%VENV_DIR%\Scripts\python.exe"
    echo set "PROBE_SCRIPT=%PROBE_SCRIPT%"
    echo if not exist "%%VENV_PY%%" set "VENV_PY=python"
    echo "%%VENV_PY%%" "%%PROBE_SCRIPT%%" ^>^> "%SENTINEL_HOME%\logs\probe.log" 2^>^&1
) > "%PROBE_WRAPPER%"

rem Register the scheduled task (runs daily at 06:00, silent, low privilege)
schtasks /query /tn "%TASK_NAME%" >nul 2>nul
if not errorlevel 1 (
    echo         Task already exists — updating...
    schtasks /delete /tn "%TASK_NAME%" /f >nul 2>nul
)

schtasks /create ^
    /tn "%TASK_NAME%" ^
    /tr "cmd /c \"%PROBE_WRAPPER%\"" ^
    /sc daily ^
    /st 06:00 ^
    /ru "%USERNAME%" ^
    /rl LIMITED ^
    /f ^
    >nul 2>nul

if errorlevel 1 (
    echo         WARNING: Could not register Task Scheduler job.
    echo         You can still run  sentinel refresh  manually to update the cloud model cache.
) else (
    echo         Task '%TASK_NAME%' registered — runs daily at 06:00.
)

rem Run an initial probe right now if OLLAMA_API_KEY is already configured
set "HAS_KEY="
if exist "%SENTINEL_HOME%\.env" (
    findstr /i "OLLAMA_API_KEY=" "%SENTINEL_HOME%\.env" | findstr /v "^#" | findstr /v "=$" >nul 2>nul
    if not errorlevel 1 set "HAS_KEY=1"
)
if not defined HAS_KEY (
    if defined OLLAMA_API_KEY set "HAS_KEY=1"
)

if defined HAS_KEY (
    echo         OLLAMA_API_KEY detected — running initial probe...
    "%VENV_PY%" "%PROBE_SCRIPT%" >> "%SENTINEL_HOME%\logs\probe.log" 2>&1
    echo         Initial probe complete. See %SENTINEL_HOME%\logs\probe.log
) else (
    echo         OLLAMA_API_KEY not yet configured.
    echo         Set it in %SENTINEL_HOME%\.env then run  sentinel refresh
    echo         (or wait for the daily task to pick it up automatically^).
)

rem ── Step 6: Generate uninstall.bat ───────────────────────────────────────────
echo.
echo   [5/6] Generating uninstall.bat...

(
    echo @echo off
    echo setlocal
    echo.
    echo echo.
    echo echo  ===============================================================
    echo echo   SENTINEL UNINSTALLER
    echo echo  ===============================================================
    echo echo.
    echo echo   This will:
    echo echo     - Remove the Task Scheduler job '%TASK_NAME%'
    echo echo     - Remove '%PROJECT_DIR%' from your user PATH
    echo echo     - Delete all Sentinel project files in '%PROJECT_DIR%'
    echo echo     - Leave ~/.sentinel ^(your sessions / settings^) intact
    echo echo.
    echo echo   Your sessions and API keys in %SENTINEL_HOME% are NOT deleted.
    echo echo   Delete that folder manually if you want a full clean removal.
    echo echo.
    echo set /p "CONFIRM=  Type YES to confirm uninstall: "
    echo if /i not "%%CONFIRM%%"=="yes" (
    echo     echo   Uninstall cancelled.
    echo     exit /b 0
    echo ^)
    echo.
    echo echo   Removing Task Scheduler job...
    echo schtasks /delete /tn "%TASK_NAME%" /f ^>nul 2^>^&1
    echo echo   Done.
    echo.
    echo echo   Removing from user PATH...
    echo powershell -NoProfile -Command "$cur = [System.Environment]::GetEnvironmentVariable('PATH','User'); $parts = $cur -split ';' ^| Where-Object { $_ -ne '%PROJECT_DIR%' }; [System.Environment]::SetEnvironmentVariable('PATH', ($parts -join ';'), 'User')"
    echo echo   Done.
    echo.
    echo echo   Deleting project files...
    echo rem  Use a detached cmd so we can delete the directory we are running from.
    echo start /b "" cmd /c "timeout /t 2 ^>nul ^& rmdir /s /q \"%PROJECT_DIR%\""
    echo echo   Sentinel has been uninstalled. You may close this window.
    echo exit /b 0
) > "%PROJECT_DIR%\uninstall.bat"

echo         Generated: %PROJECT_DIR%\uninstall.bat

rem ── Step 7: Create .env template if it does not exist ────────────────────────
if not exist "%SENTINEL_HOME%\.env" (
    (
        echo # Sentinel environment variables
        echo # Generated by installer — fill in your keys here.
        echo.
        echo # Required for online mode
        echo # OLLAMA_API_KEY=
        echo.
        echo # Optional external provider fallbacks
        echo # ANTHROPIC_API_KEY=
        echo # OPENAI_API_KEY=
        echo # GOOGLE_API_KEY=
        echo.
        echo # Uncomment to default to online mode on every launch
        echo # SENTINEL_MODE=online
    ) > "%SENTINEL_HOME%\.env"
    echo         Created: %SENTINEL_HOME%\.env  (add your API keys here^)
)

rem ── Done ─────────────────────────────────────────────────────────────────────
echo.
echo   [6/6] Installation complete!
echo.
echo  ===================================================================
echo   Sentinel is ready.
echo.
echo   Usage (open a NEW terminal window first so PATH takes effect^):
echo     sentinel                       start Sentinel
echo     sentinel --online              start in online mode
echo     sentinel refresh               refresh cloud model cache
echo.
echo   To configure API keys:
echo     %SENTINEL_HOME%\.env
echo.
echo   To uninstall:
echo     %PROJECT_DIR%\uninstall.bat
echo  ===================================================================
echo.

rem ── Self-delete install.bat ───────────────────────────────────────────────────
rem  Schedule deletion via a detached cmd after this process exits.
echo   Removing install.bat...
start /b "" cmd /c "timeout /t 2 >nul & del /f /q ""%~f0"""
exit /b 0
