"""agent_action.py — Sentinel AgentAction dataclass.

Defines the unit of work that every agent *generates* but never executes
directly.  The ExecutionEngine (or Supervisor) is responsible for
dispatching actions to the ToolRegistry.

Action types
------------
``tool_call``
    Request that the ToolRegistry invoke a specific tool.
    ``payload["tool"]``   — registered tool name (str)
    ``payload["params"]`` — parameter dict forwarded to the tool

``delegate``
    Pass control to another agent for a sub-task.
    ``payload["target_agent"]`` — agent identifier string
    ``payload["task"]``         — task dict for the target agent

``message``
    Emit an informational or reasoning message (no execution side-effect).
    ``payload["content"]`` — the text of the message

``decision``
    Record a branching choice made by the agent.
    ``payload["choice"]``     — chosen option label
    ``payload["options"]``    — all candidate options (list)
    ``payload["rationale"]``  — why this choice was made

``abort``
    Signal that the current plan/step should be halted.
    ``payload["reason"]`` — human-readable abort reason

``noop``
    Explicit no-operation placeholder (useful for testing).
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from typing import Any, Dict, Optional

# All valid action_type values.
ACTION_TYPES = frozenset(
    {"tool_call", "delegate", "message", "decision", "abort", "noop"}
)


@dataclass
class AgentAction:
    """A single action generated by an agent.

    Agents build and return lists of :class:`AgentAction` instances from their
    :py:meth:`~BaseAgent.run` implementation.  The action is never executed
    inside the agent; it is handed to the ExecutionEngine for dispatch.

    Attributes:
        action_type: One of the :data:`ACTION_TYPES` string constants.
        payload: Arbitrary data carried by the action (tool name + params,
            delegate target, message body, etc.).
        agent: Name of the agent that created this action.
        step_id: Unique identifier for the plan step this action belongs to.
        action_id: Auto-generated UUID identifying this specific action.
        rationale: Optional human-readable explanation of why this action was
            chosen, useful for explainability and debugging.
    """

    action_type: str
    payload: Dict[str, Any] = field(default_factory=dict)
    agent: str = ""
    step_id: str = ""
    action_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    rationale: str = ""

    # ------------------------------------------------------------------
    # Validation
    # ------------------------------------------------------------------

    def __post_init__(self) -> None:
        if self.action_type not in ACTION_TYPES:
            raise ValueError(
                f"Invalid action_type '{self.action_type}'.  "
                f"Must be one of: {sorted(ACTION_TYPES)}"
            )

    # ------------------------------------------------------------------
    # Convenience constructors
    # ------------------------------------------------------------------

    @classmethod
    def tool_call(
        cls,
        tool: str,
        params: Dict[str, Any],
        *,
        agent: str = "",
        step_id: str = "",
        rationale: str = "",
    ) -> "AgentAction":
        """Create a ``tool_call`` action."""
        return cls(
            action_type="tool_call",
            payload={"tool": tool, "params": params},
            agent=agent,
            step_id=step_id,
            rationale=rationale,
        )

    @classmethod
    def delegate(
        cls,
        target_agent: str,
        task: Dict[str, Any],
        *,
        agent: str = "",
        step_id: str = "",
        rationale: str = "",
    ) -> "AgentAction":
        """Create a ``delegate`` action."""
        return cls(
            action_type="delegate",
            payload={"target_agent": target_agent, "task": task},
            agent=agent,
            step_id=step_id,
            rationale=rationale,
        )

    @classmethod
    def message(
        cls,
        content: str,
        *,
        agent: str = "",
        step_id: str = "",
    ) -> "AgentAction":
        """Create a ``message`` action."""
        return cls(
            action_type="message",
            payload={"content": content},
            agent=agent,
            step_id=step_id,
        )

    @classmethod
    def decision(
        cls,
        choice: str,
        options: list,
        rationale: str = "",
        *,
        agent: str = "",
        step_id: str = "",
    ) -> "AgentAction":
        """Create a ``decision`` action."""
        return cls(
            action_type="decision",
            payload={"choice": choice, "options": options, "rationale": rationale},
            agent=agent,
            step_id=step_id,
            rationale=rationale,
        )

    @classmethod
    def abort(
        cls,
        reason: str,
        *,
        agent: str = "",
        step_id: str = "",
    ) -> "AgentAction":
        """Create an ``abort`` action."""
        return cls(
            action_type="abort",
            payload={"reason": reason},
            agent=agent,
            step_id=step_id,
            rationale=reason,
        )

    @classmethod
    def noop(cls, *, agent: str = "", step_id: str = "") -> "AgentAction":
        """Create a ``noop`` action."""
        return cls(action_type="noop", agent=agent, step_id=step_id)

    # ------------------------------------------------------------------
    # Serialisation
    # ------------------------------------------------------------------

    def to_dict(self) -> Dict[str, Any]:
        """Serialise this action to a plain dict."""
        return {
            "action_id": self.action_id,
            "action_type": self.action_type,
            "agent": self.agent,
            "step_id": self.step_id,
            "payload": self.payload,
            "rationale": self.rationale,
        }

    def __repr__(self) -> str:  # pragma: no cover
        return (
            f"AgentAction(type={self.action_type!r}, agent={self.agent!r}, "
            f"step={self.step_id!r}, id={self.action_id[:8]})"
        )
